[project]
name = "phasarr"
version = "1.0.0"
description = "Video organiser/manager for websites supported by yt-dlp."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"